# Project title
# Student Course Enrollment management system
/* Business problem: In a training institute the data is stored in excel file. 
As the number of students increasing manually analyzing/tracking the data is difficult */
/* Objective:
We need a system which tracks the student details, courses, enrollments, instructors which is easy to track the details*/
CREATE DATABASE SQLPROJECT;
USE SQLPROJECT;
CREATE TABLE Students(StudentID INT Primary key,
StudentName VARCHAR(20),
Gender varchar(20),
Age int,
City VARCHAR(20),
Email varchar(20),
Phone VARCHAR(20),
JoiningDate Date);
select * from students;
CREATE TABLE Instructors(InstructorID int Primary key,
InstructorName Varchar(20),
Department varchar(20),
Experience int);
select * from Instructors;
CREATE Table Courses(CourseID Int primary key,
CourseName varchar(20),
DurationMonth int,
Fee DECIMAL(10,2),
InstructorID int,
FOREIGN KEY (InstructorID)
references Instructors(InstructorID));
select * from courses;

CREATE table enrollments(EnrollmentID int primary key,
StudentID int,
CourseID int,
EnrollmentDate Date,
CompletionStatus Varchar(20),
Marks int,
Foreign key (StudentID)
References Students(StudentID),
Foreign key (CourseID)
References Courses(CourseID));
select * from enrollments;


# Business Analyzing questions
# 1.Total number of students
select count(*) as total_students
from students;
# Insight
# There are total 100 students in the institute

# 2.Total number of Courses
Select count(*) as total_courses
from courses;

# There are total 5 courses there in the institute

# 3.Total number of instructors
select count(*) as total_instructors
from instructors;
# There are total 5 instructors in the institute

# 4. Courses with fee greater than 5000
select * from courses
where fee>5000;

#  For python,power bi and data analytics courses fee is more than 5000

# 5. Students enrolled in each course
select 
c.coursename,
count(e.studentid) as total_students
from courses c
join enrollments e
on c.courseid=e.courseid
group by c.coursename;
# Most of the students are enrolled dor data analytics

#6. List students with their Courses
Select s.studentname,
c.coursename
from Students s
join enrollments e
on s.studentid=e.studentid
join courses c
on e.courseid=c.courseid;

# 7.Students who completed their course
select s.studentname,
c.coursename,
e.CompletionStatus
from students s
join enrollments e
on s.studentid=e.studentid
join courses c
on c.courseid=e.courseid
where CompletionStatus='Completed';

#8. Students who are still studying
select s.studentname,
c.coursename,
e.CompletionStatus
from students s
join enrollments e
on s.studentid=e.studentid
join courses c
on c.courseid=e.courseid
where CompletionStatus='Ongoing';

# 9.City wise student count
select city,count(*) as total_students
from Students
group by city;

# using sql query I have analyzed that most of the students are from hyderabad

# 10. Revenue generated by each course
select c.coursename,
count(e.studentid) * c.fee as revenue
from enrollments e
join courses c
on e.courseid=c.courseid
group by c.coursename,c.fee;

# Highest revenue is generated from the course data analyics
# Least revenue is generated from the course excel.


